##-------------------------------------
# ReadMe
#-------------------------------------
# ~/.tmux.conf
# 以下のように省略可能
# set-option        => set
# set-window-option => setw

#-------------------------------------
# キーバインド設定
#-------------------------------------
# prefixのキーバインドを変更
# unbind-key    C-b
# set -g prefix C-t

# ~/.tmux.confの読み込みキーバインド
unbind r
bind   r source-file ~/.tmux.conf \; display-message "tmux RELOADED!!"

# tmuxセッションをkillする時に下部に確認ダイアログを表示する
unbind K
bind   K confirm-before "kill-window"

# prefix + -で水平分割
bind - split-window -v

# prefix + |で垂直分割
bind | split-window -h

# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

#-------------------------------------
# 基本設定
#-------------------------------------
if-shell "uname | grep -q Darwin" "set-option -g default-shell /usr/local/bin/fish"

if-shell "uname | grep -q Linux" "set-option -g default-shell /usr/bin/fish"

# disable sound bell
set -g bell-action none
# disable visual bell
set -g visual-bell off

set -sg escape-time 1

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windowset -g base-index 1

set -g set-titles on          # set terminal title

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g mouse on
setw -g mode-key vi

#-------------------------------------
# 色設定
# カラーコードは以下コマンドで確認
# ~/dotfiles/tmux/tmux-powerline/color_palette.sh
#-------------------------------------
set -g default-terminal "screen-256color"

set -g status-style fg=cyan,bg=black

setw -g window-status-current-style fg=black,bg=cyan,bold

set -g pane-active-border-style fg=black,bg=cyan

setw -g pane-active-border-style ""

#-------------------------------------
# ステータス設定
#-------------------------------------
set-option -g status-position top

set-option -g status-interval 5

set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 90
set-option -g status-right-length 90
set-option -g status-left "#(~/dotfiles/tmux/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/dotfiles/tmux/tmux-powerline/powerline.sh right)"

# window-status のフォーマットを指定
setw -g window-status-format " #I "

# カレントウィンドウの window-status のフォーマットを指定
setw -g window-status-current-format "#[fg=cyan,bg=black,bold] #I #[default]"
