[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "P"
run  = "paste"
desc = "Default paste (into CWD)"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = 'cd /mnt/c/Users/yellow/Downloads'
desc = "Go to Windows Downloads"

[[mgr.prepend_keymap]]
on = "r"
run = "bulk_rename"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "R"
run = "rename --hovered"
desc = "Rename hovered file"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = [ "close", "plugin ime-off" ]
desc = "Cancel input and turn IME off"

[[input.prepend_keymap]]
on   = "<Enter>"
run  = [ "close --submit", "plugin ime-off" ]
desc = "Submit input and turn IME off"
